robot1:
  amcl:
    ros__parameters:
      use_sim_time: True
      base_frame_id: "base_footprint"
      global_frame_id: "map"
      odom_frame_id: "odom"
      scan_topic: /robot1/scan
      tf_broadcast: true
      alpha1: 0.2
      alpha2: 0.2
      alpha3: 0.2
      alpha4: 0.2
      alpha5: 0.2
      beta: 0.02
      lambda_short: 0.05
      max_beams: 60
      max_particles: 2000
      min_particles: 500
      pf_err: 0.05
      pf_z: 0.99
      recovery_alpha_fast: 0.0
      recovery_alpha_slow: 0.0
      resample_interval: 1
      robot_model_type: "differential"
      save_pose_rate: 0.5
      sigma_hit: 0.2
      transform_tolerance: 1.0
      update_min_a: 0.2
      update_min_d: 0.25
      z_hit: 0.5
      z_max: 0.05
      z_rand: 0.5
      z_short: 0.05

  controller_server:
    ros__parameters:
      use_sim_time: True
      odom_topic: /robot1/odom

  local_costmap:
    local_costmap:
      ros__parameters:
        use_sim_time: True
        global_frame: robot1/odom
        robot_base_frame: robot1/base_link
        scan:
          topic: /robot1/scan
        observation_sources: scan
        scan: {data_type: LaserScan, topic: /robot1/scan, marking: true, clearing: true}

  global_costmap:
    global_costmap:
      ros__parameters:
        use_sim_time: True
        global_frame: map
        robot_base_frame: robot1/base_link
        scan:
          topic: /robot1/scan
        observation_sources: scan
        scan: {data_type: LaserScan, topic: /robot1/scan, marking: true, clearing: true}

  bt_navigator:
    ros__parameters:
      use_sim_time: True
      global_frame: robot1/map
      robot_base_frame: robot1/base_link

  planner_server:
    ros__parameters:
      use_sim_time: True

  smoother_server:
    ros__parameters:
      use_sim_time: True

  behavior_server:
    ros__parameters:
      use_sim_time: True
      global_frame: robot1/odom
      robot_base_frame: robot1/base_link

  waypoint_follower:
    ros__parameters:
      use_sim_time: True

  velocity_smoother:
    ros__parameters:
      use_sim_time: True
