robot3:
  amcl:
    ros__parameters:
      use_sim_time: True
      base_frame_id: "robot3/base_footprint"
      global_frame_id: "robot3/map"
      odom_frame_id: "robot3/odom"
      scan_topic: /robot3/scan

  controller_server:
    ros__parameters:
      use_sim_time: True
      odom_topic: /robot3/odom

  local_costmap:
    local_costmap:
      ros__parameters:
        use_sim_time: True
        global_frame: robot3/odom
        robot_base_frame: robot3/base_link
        scan:
          topic: /robot3/scan

  global_costmap:
    global_costmap:
      ros__parameters:
        use_sim_time: True
        global_frame: robot3/map
        robot_base_frame: robot3/base_link
        scan:
          topic: /robot3/scan

  bt_navigator:
    ros__parameters:
      use_sim_time: True
      global_frame: robot3/map
      robot_base_frame: robot3/base_link

  planner_server:
    ros__parameters:
      use_sim_time: True

  smoother_server:
    ros__parameters:
      use_sim_time: True

  behavior_server:
    ros__parameters:
      use_sim_time: True
      global_frame: robot3/odom
      robot_base_frame: robot3/base_link

  waypoint_follower:
    ros__parameters:
      use_sim_time: True

  velocity_smoother:
    ros__parameters:
      use_sim_time: True
